#!/usr/bin/env bash
#
# Record a demo video for the README.
#
# Requires https://asciinema.org/docs/installation
# Run in a terminal of size: 120 width, 30 height to match the
# size specified in render-cast.
#

set -eu -o pipefail

export PS1="$ "
mkdir -p demo
name="${1-demo.cast}"
asciinema rec \
    --overwrite \
    --idle-time-limit 2 \
    -c scripts/demo \
    "demo/$name"
