#!/usr/bin/env bash
set -eu -o pipefail

paths=${@:-./...}
TESTFLAGS=${TESTFLAGS-}
TESTTIMEOUT=${TESTTIMEOUT-30s}
./dist/gotestsum \
    --junitfile junit.xml \
    --format short-verbose -- \
    -test.timeout "$TESTTIMEOUT" $TESTFLAGS $paths
