#!/usr/bin/env bash
set -eu -o pipefail

paths=${@:-$(go list ./... | grep -v '/vendor/')}
TESTFLAGS=${TESTFLAGS-}
TESTTIMEOUT=${TESTTIMEOUT-30s}
./dist/gotestsum --format short-verbose -- \
    -test.timeout "$TESTTIMEOUT" $TESTFLAGS $paths
