#!/usr/bin/env bash
exec filewatcher \
    -e create -e write \
    -x 'vendor' \
    -x 'scripts' \
    -x '**/*___jb_tmp___' \
    -x '**/*___jb_old___' \
    ./dist/gotestsum --format short-verbose -- -test.timeout "10s" './${dir}'
