name: ci

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup git
        # required to run tests on windows
        run: |
          git config --global core.autocrlf false
          git config --global core.symlinks true
      - name: Fetch Repository
        uses: actions/checkout@v5
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - run: go build .
      - run: ./gotestsum -f testname -- ./... -race -count=1
      - name: "DEBUG: Showing new github actions concise format"
        run: ./gotestsum -f github-actions-concise -- ./... -race -count=1
