name: ci

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        go-version: [stable, oldstable]
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup git
        # required to run tests on windows
        run: |
          git config --global core.autocrlf false
          git config --global core.symlinks true
      - name: Fetch Repository
        uses: actions/checkout@v5
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - run: go build .
      - run: ./gotestsum -f testname -- ./... -race -count=1
      - name: "DEBUG: Showing original github actions format"
        run: ./gotestsum -f github-actions -- -tags=stubpkg -count=1 ./testjson/internal/...
      - name: "DEBUG: Showing new github actions concise format"
        run: ./gotestsum -f github-actions-concise -- ./... -race -count=1
